Add minimal xs test (test includes and compilation)
plicease/Alien-libuuid pull request #7
Opened 2020-05-08 14:12 UTC by thibaultduponchelle

Hello :smiley: 

I don't know anything about XS but I tried to implement this minimal XS test for Alien::libuuid (issue #5)

It is only "include + compilation" but should be worth to merge anyway.

Best regards

Thibault

2020-05-19 16:16 UTC, plicease commented
The XS should expose `uuid_generate_random` and the Perl code should try to join it in a subtest (similar to the ffi test):

https://github.com/plicease/Alien-libuuid/blob/master/t/alien_libuuid.t

This helps spot linker errors.

I usually keep the xs and ffi tests in one .t file since they are usually short.

2020-05-19 16:16 UTC, plicease requested changes
please add a test to call a uuid function.  The equivalent to what the ffi test is doing basically, but via XS.

2020-05-20 08:31 UTC, thibaultduponchelle commented
Hello,

I added 2 xs (one to test each include) and call the uuid_generate_random function.

Regards.

Thibault

2020-05-28 14:53 UTC, plicease approved these changes

2020-05-28 14:53 UTC, merged